bool snapshot_mode            # boolean indicating whether we are in snapshot mode or not
string snapshot_name          # name of the loaded snapshot
string system_id                  # Hostname of the machine that generated the snapshot
string pickit_version             # Git hash in case of compilation from source OR pickit version
string robot_type                 # Robot type from the socket interface.
