(cl:in-package im_pickit_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CONTENT-VAL
          CONTENT
          ENCODER_STAMP-VAL
          ENCODER_STAMP
          ROBOT_TO_CAMERA_TF-VAL
          ROBOT_TO_CAMERA_TF
          CAMERA_TO_REFERENCE_TF-VAL
          CAMERA_TO_REFERENCE_TF
          CLOUD_CAPTURING_DURATION-VAL
          CLOUD_CAPTURING_DURATION
          CLUSTERING_METHOD-VAL
          CLUSTERING_METHOD
          N_REJECTED_CLUSTERS-VAL
          N_REJECTED_CLUSTERS
          CLUSTERING_DURATION-VAL
          CLUSTERING_DURATION
          CALCULATION_TIME-VAL
          CALCULATION_TIME
          N_VALID_OBJECTS-VAL
          N_VALID_OBJECTS
          N_REJECTED_OBJECTS-VAL
          N_REJECTED_OBJECTS
          OBJECTS-VAL
          OBJECTS
))