(cl:in-package im_pickit_msgs-msg)
(cl:export '(CALIBRATION_PLATE_VISIBLE-VAL
          CALIBRATION_PLATE_VISIBLE
          CALIBRATION_REQUEST_RECEIVED-VAL
          CALIBRATION_REQUEST_RECEIVED
          CALIBRATION_PLATE_LOCALIZED-VAL
          CALIBRATION_PLATE_LOCALIZED
          CALIBRATION_INPUT_POSES_RECEIVED-VAL
          CALIBRATION_INPUT_POSES_RECEIVED
          CALIBRATION_CALCULATED-VAL
          CALIBRATION_CALCULATED
))