// Generated by gencpp from file im_pickit_msgs/CalibrationStatus.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_CALIBRATIONSTATUS_H
#define IM_PICKIT_MSGS_MESSAGE_CALIBRATIONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct CalibrationStatus_
{
  typedef CalibrationStatus_<ContainerAllocator> Type;

  CalibrationStatus_()
    : calibration_plate_visible(false)
    , calibration_request_received(false)
    , calibration_plate_localized(false)
    , calibration_input_poses_received(false)
    , calibration_calculated(false)  {
    }
  CalibrationStatus_(const ContainerAllocator& _alloc)
    : calibration_plate_visible(false)
    , calibration_request_received(false)
    , calibration_plate_localized(false)
    , calibration_input_poses_received(false)
    , calibration_calculated(false)  {
  (void)_alloc;
    }



   typedef uint8_t _calibration_plate_visible_type;
  _calibration_plate_visible_type calibration_plate_visible;

   typedef uint8_t _calibration_request_received_type;
  _calibration_request_received_type calibration_request_received;

   typedef uint8_t _calibration_plate_localized_type;
  _calibration_plate_localized_type calibration_plate_localized;

   typedef uint8_t _calibration_input_poses_received_type;
  _calibration_input_poses_received_type calibration_input_poses_received;

   typedef uint8_t _calibration_calculated_type;
  _calibration_calculated_type calibration_calculated;




  typedef boost::shared_ptr< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrationStatus_

typedef ::im_pickit_msgs::CalibrationStatus_<std::allocator<void> > CalibrationStatus;

typedef boost::shared_ptr< ::im_pickit_msgs::CalibrationStatus > CalibrationStatusPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::CalibrationStatus const> CalibrationStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb9e08f442b346d90200848306f7f520";
  }

  static const char* value(const ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb9e08f442b346d9ULL;
  static const uint64_t static_value2 = 0x0200848306f7f520ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/CalibrationStatus";
  }

  static const char* value(const ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Copyright Pick-it NV 2017\n\
## This message contains Calibration status information  ##\n\
\n\
bool calibration_plate_visible\n\
bool calibration_request_received\n\
bool calibration_plate_localized\n\
bool calibration_input_poses_received\n\
\n\
bool calibration_calculated\n\
";
  }

  static const char* value(const ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.calibration_plate_visible);
      stream.next(m.calibration_request_received);
      stream.next(m.calibration_plate_localized);
      stream.next(m.calibration_input_poses_received);
      stream.next(m.calibration_calculated);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrationStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::CalibrationStatus_<ContainerAllocator>& v)
  {
    s << indent << "calibration_plate_visible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_plate_visible);
    s << indent << "calibration_request_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_request_received);
    s << indent << "calibration_plate_localized: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_plate_localized);
    s << indent << "calibration_input_poses_received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_input_poses_received);
    s << indent << "calibration_calculated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.calibration_calculated);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_CALIBRATIONSTATUS_H
