// Generated by gencpp from file im_pickit_msgs/CameraState.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_CAMERASTATE_H
#define IM_PICKIT_MSGS_MESSAGE_CAMERASTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct CameraState_
{
  typedef CameraState_<ContainerAllocator> Type;

  CameraState_()
    : state(0)  {
    }
  CameraState_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;


    enum { STATE_REGISTERED = 1u };
     enum { STATE_CONNECTED = 2u };
     enum { STATE_DISCONNECTED = 3u };
 

  typedef boost::shared_ptr< ::im_pickit_msgs::CameraState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::CameraState_<ContainerAllocator> const> ConstPtr;

}; // struct CameraState_

typedef ::im_pickit_msgs::CameraState_<std::allocator<void> > CameraState;

typedef boost::shared_ptr< ::im_pickit_msgs::CameraState > CameraStatePtr;
typedef boost::shared_ptr< ::im_pickit_msgs::CameraState const> CameraStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::CameraState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::CameraState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CameraState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CameraState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CameraState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f0b89c087f6efa23b45a421459a1b74";
  }

  static const char* value(const ::im_pickit_msgs::CameraState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f0b89c087f6efa2ULL;
  static const uint64_t static_value2 = 0x3b45a421459a1b74ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/CameraState";
  }

  static const char* value(const ::im_pickit_msgs::CameraState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STATE_REGISTERED    = 1\n\
uint8 STATE_CONNECTED     = 2\n\
uint8 STATE_DISCONNECTED  = 3\n\
\n\
uint8 state   # Camera state\n\
";
  }

  static const char* value(const ::im_pickit_msgs::CameraState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::CameraState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::CameraState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_CAMERASTATE_H
