// Generated by gencpp from file im_pickit_msgs/CameraConfig.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_CAMERACONFIG_H
#define IM_PICKIT_MSGS_MESSAGE_CAMERACONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct CameraConfig_
{
  typedef CameraConfig_<ContainerAllocator> Type;

  CameraConfig_()
    : name()
    , serial()  {
    }
  CameraConfig_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , serial(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _serial_type;
  _serial_type serial;




  typedef boost::shared_ptr< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> const> ConstPtr;

}; // struct CameraConfig_

typedef ::im_pickit_msgs::CameraConfig_<std::allocator<void> > CameraConfig;

typedef boost::shared_ptr< ::im_pickit_msgs::CameraConfig > CameraConfigPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::CameraConfig const> CameraConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::CameraConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4914eb207f0463464c48e14410d8a949";
  }

  static const char* value(const ::im_pickit_msgs::CameraConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4914eb207f046346ULL;
  static const uint64_t static_value2 = 0x4c48e14410d8a949ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/CameraConfig";
  }

  static const char* value(const ::im_pickit_msgs::CameraConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message fields\n\
string name                                 # name (=namespace) of the camera (unique!)\n\
string serial                               # Serial number.\n\
";
  }

  static const char* value(const ::im_pickit_msgs::CameraConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.serial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::CameraConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::CameraConfig_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "serial: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.serial);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_CAMERACONFIG_H
