// Generated by gencpp from file im_pickit_msgs/CheckForObjects.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_CHECKFOROBJECTS_H
#define IM_PICKIT_MSGS_MESSAGE_CHECKFOROBJECTS_H

#include <ros/service_traits.h>


#include <im_pickit_msgs/CheckForObjectsRequest.h>
#include <im_pickit_msgs/CheckForObjectsResponse.h>


namespace im_pickit_msgs
{

struct CheckForObjects
{

typedef CheckForObjectsRequest Request;
typedef CheckForObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckForObjects
} // namespace im_pickit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_pickit_msgs::CheckForObjects > {
  static const char* value()
  {
    return "991a96571e9f4e20d906edfcd9ce097d";
  }

  static const char* value(const ::im_pickit_msgs::CheckForObjects&) { return value(); }
};

template<>
struct DataType< ::im_pickit_msgs::CheckForObjects > {
  static const char* value()
  {
    return "im_pickit_msgs/CheckForObjects";
  }

  static const char* value(const ::im_pickit_msgs::CheckForObjects&) { return value(); }
};


// service_traits::MD5Sum< ::im_pickit_msgs::CheckForObjectsRequest> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::CheckForObjects > 
template<>
struct MD5Sum< ::im_pickit_msgs::CheckForObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::CheckForObjects >::value();
  }
  static const char* value(const ::im_pickit_msgs::CheckForObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::CheckForObjectsRequest> should match 
// service_traits::DataType< ::im_pickit_msgs::CheckForObjects > 
template<>
struct DataType< ::im_pickit_msgs::CheckForObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::CheckForObjects >::value();
  }
  static const char* value(const ::im_pickit_msgs::CheckForObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_pickit_msgs::CheckForObjectsResponse> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::CheckForObjects > 
template<>
struct MD5Sum< ::im_pickit_msgs::CheckForObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::CheckForObjects >::value();
  }
  static const char* value(const ::im_pickit_msgs::CheckForObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::CheckForObjectsResponse> should match 
// service_traits::DataType< ::im_pickit_msgs::CheckForObjects > 
template<>
struct DataType< ::im_pickit_msgs::CheckForObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::CheckForObjects >::value();
  }
  static const char* value(const ::im_pickit_msgs::CheckForObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_CHECKFOROBJECTS_H
