// Generated by gencpp from file im_pickit_msgs/CopyCalibrationRequest.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_COPYCALIBRATIONREQUEST_H
#define IM_PICKIT_MSGS_MESSAGE_COPYCALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct CopyCalibrationRequest_
{
  typedef CopyCalibrationRequest_<ContainerAllocator> Type;

  CopyCalibrationRequest_()
    : source_setup_file()
    , target_setup_file()  {
    }
  CopyCalibrationRequest_(const ContainerAllocator& _alloc)
    : source_setup_file(_alloc)
    , target_setup_file(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _source_setup_file_type;
  _source_setup_file_type source_setup_file;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _target_setup_file_type;
  _target_setup_file_type target_setup_file;




  typedef boost::shared_ptr< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CopyCalibrationRequest_

typedef ::im_pickit_msgs::CopyCalibrationRequest_<std::allocator<void> > CopyCalibrationRequest;

typedef boost::shared_ptr< ::im_pickit_msgs::CopyCalibrationRequest > CopyCalibrationRequestPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::CopyCalibrationRequest const> CopyCalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3a35b241129d987f4b8abb66896a608";
  }

  static const char* value(const ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3a35b241129d987ULL;
  static const uint64_t static_value2 = 0xf4b8abb66896a608ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/CopyCalibrationRequest";
  }

  static const char* value(const ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string    source_setup_file\n\
string    target_setup_file\n\
";
  }

  static const char* value(const ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source_setup_file);
      stream.next(m.target_setup_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CopyCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::CopyCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "source_setup_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.source_setup_file);
    s << indent << "target_setup_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.target_setup_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_COPYCALIBRATIONREQUEST_H
