// Generated by gencpp from file im_pickit_msgs/LoadConfig.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_LOADCONFIG_H
#define IM_PICKIT_MSGS_MESSAGE_LOADCONFIG_H

#include <ros/service_traits.h>


#include <im_pickit_msgs/LoadConfigRequest.h>
#include <im_pickit_msgs/LoadConfigResponse.h>


namespace im_pickit_msgs
{

struct LoadConfig
{

typedef LoadConfigRequest Request;
typedef LoadConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadConfig
} // namespace im_pickit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_pickit_msgs::LoadConfig > {
  static const char* value()
  {
    return "eab8b02e16fe6a8a2dd0ff58db907dfe";
  }

  static const char* value(const ::im_pickit_msgs::LoadConfig&) { return value(); }
};

template<>
struct DataType< ::im_pickit_msgs::LoadConfig > {
  static const char* value()
  {
    return "im_pickit_msgs/LoadConfig";
  }

  static const char* value(const ::im_pickit_msgs::LoadConfig&) { return value(); }
};


// service_traits::MD5Sum< ::im_pickit_msgs::LoadConfigRequest> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::LoadConfig > 
template<>
struct MD5Sum< ::im_pickit_msgs::LoadConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::LoadConfig >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::LoadConfigRequest> should match 
// service_traits::DataType< ::im_pickit_msgs::LoadConfig > 
template<>
struct DataType< ::im_pickit_msgs::LoadConfigRequest>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::LoadConfig >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_pickit_msgs::LoadConfigResponse> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::LoadConfig > 
template<>
struct MD5Sum< ::im_pickit_msgs::LoadConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::LoadConfig >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::LoadConfigResponse> should match 
// service_traits::DataType< ::im_pickit_msgs::LoadConfig > 
template<>
struct DataType< ::im_pickit_msgs::LoadConfigResponse>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::LoadConfig >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_LOADCONFIG_H
