// Generated by gencpp from file im_pickit_msgs/LoadConfigRequest.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_LOADCONFIGREQUEST_H
#define IM_PICKIT_MSGS_MESSAGE_LOADCONFIGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct LoadConfigRequest_
{
  typedef LoadConfigRequest_<ContainerAllocator> Type;

  LoadConfigRequest_()
    : config_type(0)
    , path()
    , set_persistent(false)  {
    }
  LoadConfigRequest_(const ContainerAllocator& _alloc)
    : config_type(0)
    , path(_alloc)
    , set_persistent(false)  {
  (void)_alloc;
    }



   typedef uint8_t _config_type_type;
  _config_type_type config_type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;

   typedef uint8_t _set_persistent_type;
  _set_persistent_type set_persistent;


    enum { CONFIG_SETUP = 1u };
     enum { CONFIG_PRODUCT = 2u };
 

  typedef boost::shared_ptr< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadConfigRequest_

typedef ::im_pickit_msgs::LoadConfigRequest_<std::allocator<void> > LoadConfigRequest;

typedef boost::shared_ptr< ::im_pickit_msgs::LoadConfigRequest > LoadConfigRequestPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::LoadConfigRequest const> LoadConfigRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "805484315e7d6c7653d6a6b5867c6cff";
  }

  static const char* value(const ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x805484315e7d6c76ULL;
  static const uint64_t static_value2 = 0x53d6a6b5867c6cffULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/LoadConfigRequest";
  }

  static const char* value(const ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 CONFIG_SETUP = 1\n\
uint8 CONFIG_PRODUCT = 2\n\
\n\
uint8     config_type\n\
string    path\n\
bool      set_persistent\n\
";
  }

  static const char* value(const ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.config_type);
      stream.next(m.path);
      stream.next(m.set_persistent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadConfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::LoadConfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "config_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.config_type);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
    s << indent << "set_persistent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.set_persistent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_LOADCONFIGREQUEST_H
