// Generated by gencpp from file im_pickit_msgs/LoadSnapshot.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_LOADSNAPSHOT_H
#define IM_PICKIT_MSGS_MESSAGE_LOADSNAPSHOT_H

#include <ros/service_traits.h>


#include <im_pickit_msgs/LoadSnapshotRequest.h>
#include <im_pickit_msgs/LoadSnapshotResponse.h>


namespace im_pickit_msgs
{

struct LoadSnapshot
{

typedef LoadSnapshotRequest Request;
typedef LoadSnapshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadSnapshot
} // namespace im_pickit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_pickit_msgs::LoadSnapshot > {
  static const char* value()
  {
    return "a6bc470520bc753be0bc358804c232a4";
  }

  static const char* value(const ::im_pickit_msgs::LoadSnapshot&) { return value(); }
};

template<>
struct DataType< ::im_pickit_msgs::LoadSnapshot > {
  static const char* value()
  {
    return "im_pickit_msgs/LoadSnapshot";
  }

  static const char* value(const ::im_pickit_msgs::LoadSnapshot&) { return value(); }
};


// service_traits::MD5Sum< ::im_pickit_msgs::LoadSnapshotRequest> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::LoadSnapshot > 
template<>
struct MD5Sum< ::im_pickit_msgs::LoadSnapshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::LoadSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::LoadSnapshotRequest> should match 
// service_traits::DataType< ::im_pickit_msgs::LoadSnapshot > 
template<>
struct DataType< ::im_pickit_msgs::LoadSnapshotRequest>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::LoadSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_pickit_msgs::LoadSnapshotResponse> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::LoadSnapshot > 
template<>
struct MD5Sum< ::im_pickit_msgs::LoadSnapshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::LoadSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadSnapshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::LoadSnapshotResponse> should match 
// service_traits::DataType< ::im_pickit_msgs::LoadSnapshot > 
template<>
struct DataType< ::im_pickit_msgs::LoadSnapshotResponse>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::LoadSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::LoadSnapshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_LOADSNAPSHOT_H
