// Generated by gencpp from file im_pickit_msgs/Object.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_OBJECT_H
#define IM_PICKIT_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>
#include <geometry_msgs/TransformStamped.h>
#include <im_pickit_msgs/ObjectModel.h>
#include <geometry_msgs/Vector3.h>
#include <im_pickit_msgs/Reliability.h>
#include <im_pickit_msgs/SubStatus.h>

namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : index(0)
    , object_tf()
    , object_pick_tf()
    , model()
    , n_points(0)
    , dimensions()
    , reliability()
    , is_valid(false)
    , is_pickable(false)
    , is_detectable(false)
    , categories()
    , substatuses()  {
    }
  Object_(const ContainerAllocator& _alloc)
    : index(0)
    , object_tf(_alloc)
    , object_pick_tf(_alloc)
    , model(_alloc)
    , n_points(0)
    , dimensions(_alloc)
    , reliability(_alloc)
    , is_valid(false)
    , is_pickable(false)
    , is_detectable(false)
    , categories(_alloc)
    , substatuses(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _index_type;
  _index_type index;

   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _object_tf_type;
  _object_tf_type object_tf;

   typedef  ::geometry_msgs::TransformStamped_<ContainerAllocator>  _object_pick_tf_type;
  _object_pick_tf_type object_pick_tf;

   typedef  ::im_pickit_msgs::ObjectModel_<ContainerAllocator>  _model_type;
  _model_type model;

   typedef uint16_t _n_points_type;
  _n_points_type n_points;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _dimensions_type;
  _dimensions_type dimensions;

   typedef  ::im_pickit_msgs::Reliability_<ContainerAllocator>  _reliability_type;
  _reliability_type reliability;

   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef uint8_t _is_pickable_type;
  _is_pickable_type is_pickable;

   typedef uint8_t _is_detectable_type;
  _is_detectable_type is_detectable;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _categories_type;
  _categories_type categories;

   typedef std::vector< ::im_pickit_msgs::SubStatus_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::im_pickit_msgs::SubStatus_<ContainerAllocator> >::other >  _substatuses_type;
  _substatuses_type substatuses;




  typedef boost::shared_ptr< ::im_pickit_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::im_pickit_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::im_pickit_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2b8ba1b2df980f0868c9ec736119a65";
  }

  static const char* value(const ::im_pickit_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2b8ba1b2df980f0ULL;
  static const uint64_t static_value2 = 0x868c9ec736119a65ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/Object";
  }

  static const char* value(const ::im_pickit_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Copyright Intermodalics 2016\n\
## This message contains all descriptive data for one object found by Pick-it ##\n\
\n\
# Object index in list associated to a single detection run.\n\
uint16                                  index\n\
\n\
# Object frame expressed with respect to a frame.\n\
geometry_msgs/TransformStamped          object_tf\n\
\n\
# Object pick frame expressed with respect to a frame.\n\
geometry_msgs/TransformStamped          object_pick_tf\n\
\n\
# Object model used for registration, reliability score calculation and more.\n\
ObjectModel                             model\n\
\n\
# Number of scene points verifying the object model.\n\
uint16                                  n_points\n\
\n\
# Object dimensions. The contents of the x, y and z elements depend on the\n\
# object type:\n\
#\n\
#  |   Type      |    X     |    Y     |    Z     |\n\
#  |-------------|----------|----------|----------|\n\
#  | CYLINDER    | length   | diameter | diameter |\n\
#  | SPHERE      | diameter | diameter | diameter |\n\
#  | RECTANGLE   | length   | width    |    0     |\n\
#  | SQUARE      | length   | length   |    0     |\n\
#  | ELLIPSE     | length   | width    |    0     |\n\
#  | CIRCLE      | diameter | diameter |    0     |\n\
#  | POINT_CLOUD | bbox X   | bbox Y   | bbox Z   |\n\
#  | BLOB        | bbox X   | bbox Y   | bbox Z   |\n\
#\n\
# where 'bbox X' means the span of the object's bounding box along the X-axis.\n\
geometry_msgs/Vector3                   dimensions\n\
\n\
# Contains scoring metrics used to quantify the goodness of a detection.\n\
Reliability                             reliability\n\
\n\
# NOTE: There is currently an inconsistency between terms used in the\n\
#       back-end vs. the front-end. The following table summarizes them to\n\
#       prevent confusion:\n\
#\n\
#       BACK-END flag  maps to ->   FRONT-END detection grid column\n\
#\n\
#       is_pickable    maps to ->   Pickable\n\
#       is_detectable  maps to ->   Valid\n\
#       is_valid       maps to ->   <None>\n\
#\n\
#       Notice in particular how the is_valid back-end flag and the Valid\n\
#       front-end detection grid column have different meanings.\n\
\n\
# Flag that evaluates to true when an object is both pickable and detectable.\n\
bool                                    is_valid\n\
\n\
# Flag that evaluates to true when an object satisfies frame alignment and\n\
# collision constraints.\n\
bool                                    is_pickable\n\
\n\
# Flag that evaluates to true when an object satisfies fitting, reliability and\n\
# size constraints.\n\
bool                                    is_detectable\n\
\n\
# List of strings describing main detection status for invalid detections\n\
# (e.g. ERROR, INVALID, UNPICKABLE).\n\
# See CATEGORY strings in StatusXxx.msg files for available categories.\n\
# The list is empty in case of a valid detection.\n\
string[]                                categories\n\
\n\
# List of substatus identifiers providing detail information for each of the\n\
# above categories. There is one substatus per category.\n\
# The list is empty in case of a valid detection.\n\
SubStatus[]                             substatuses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TransformStamped\n\
# This expresses a transform from coordinate frame header.frame_id\n\
# to the coordinate frame child_frame_id\n\
#\n\
# This message is mostly used by the \n\
# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n\
# See its documentation for more information.\n\
\n\
Header header\n\
string child_frame_id # the frame id of the child frame\n\
Transform transform\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: im_pickit_msgs/ObjectModel\n\
# Copyright (c) 2017, Pick-it NV.\n\
# All rights reserved.\n\
\n\
# Definition of different object models used for registration, reliability score calculation and more.\n\
\n\
# Unspecified\n\
uint8 NONE          = 0\n\
\n\
# 2D models:\n\
uint8 SQUARE        = 21\n\
uint8 RECTANGLE     = 22\n\
uint8 CIRCLE        = 23\n\
uint8 ELLIPSE       = 24\n\
\n\
# 3D models:\n\
uint8 CYLINDER      = 32\n\
uint8 SPHERE        = 33\n\
uint8 POINT_CLOUD   = 35  # Object model given as point cloud (Pickit-Teach).\n\
\n\
# Other models:\n\
uint8 BLOB          = 50  # Object without specified shape -> No object fitting is performed.\n\
\n\
# Models of internal use only:\n\
uint8 CLUSTER       = 250\n\
\n\
uint8 type  # Model type, takes one of the above defined models types as value.\n\
\n\
================================================================================\n\
MSG: im_pickit_msgs/Reliability\n\
## Contains all parameters describing reliability of detected object\n\
## Values expressed as confidence levels ranging from 0.0 to 1.0\n\
\n\
## Ratio of inlier points close to the border of the \"Intermodalics hole\" and\n\
## all points of the \"Intermodalics hole\".\n\
ReliabilityValue scene_coverage_2d\n\
\n\
## Ratio of inlier points to all points in the cluster.\n\
ReliabilityValue scene_coverage_3d\n\
\n\
### TODO(@wannesvanloock): Add description pls.\n\
ReliabilityValue model_contour_coverage_2d\n\
### TODO(@wannesvanloock): Add description pls.\n\
ReliabilityValue model_surface_coverage_2d\n\
\n\
## 3D reliability of the matched model\n\
ReliabilityValue model_coverage_3d\n\
\n\
================================================================================\n\
MSG: im_pickit_msgs/ReliabilityValue\n\
float64 value\n\
float64 required_value\n\
\n\
# mostly we work with lower limits so usually this is false\n\
bool has_upper_limit     \n\
================================================================================\n\
MSG: im_pickit_msgs/SubStatus\n\
# Rejected object substatus:\n\
#  - StatusUnpickable (orange)\n\
#  - StatusInvalid (red)\n\
#  - StatusDiscarded (no marker)\n\
\n\
uint16 substatus\n\
string detail\n\
";
  }

  static const char* value(const ::im_pickit_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.object_tf);
      stream.next(m.object_pick_tf);
      stream.next(m.model);
      stream.next(m.n_points);
      stream.next(m.dimensions);
      stream.next(m.reliability);
      stream.next(m.is_valid);
      stream.next(m.is_pickable);
      stream.next(m.is_detectable);
      stream.next(m.categories);
      stream.next(m.substatuses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::Object_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.index);
    s << indent << "object_tf: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.object_tf);
    s << indent << "object_pick_tf: ";
    s << std::endl;
    Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.object_pick_tf);
    s << indent << "model: ";
    s << std::endl;
    Printer< ::im_pickit_msgs::ObjectModel_<ContainerAllocator> >::stream(s, indent + "  ", v.model);
    s << indent << "n_points: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.n_points);
    s << indent << "dimensions: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.dimensions);
    s << indent << "reliability: ";
    s << std::endl;
    Printer< ::im_pickit_msgs::Reliability_<ContainerAllocator> >::stream(s, indent + "  ", v.reliability);
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "is_pickable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_pickable);
    s << indent << "is_detectable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_detectable);
    s << indent << "categories[]" << std::endl;
    for (size_t i = 0; i < v.categories.size(); ++i)
    {
      s << indent << "  categories[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.categories[i]);
    }
    s << indent << "substatuses[]" << std::endl;
    for (size_t i = 0; i < v.substatuses.size(); ++i)
    {
      s << indent << "  substatuses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::im_pickit_msgs::SubStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.substatuses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_OBJECT_H
