// Generated by gencpp from file im_pickit_msgs/PickitStatus.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_PICKITSTATUS_H
#define IM_PICKIT_MSGS_MESSAGE_PICKITSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct PickitStatus_
{
  typedef PickitStatus_<ContainerAllocator> Type;

  PickitStatus_()
    : state()
    , setup_file()
    , product_file()
    , setup_changed(false)
    , product_changed(false)  {
    }
  PickitStatus_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , setup_file(_alloc)
    , product_file(_alloc)
    , setup_changed(false)
    , product_changed(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _setup_file_type;
  _setup_file_type setup_file;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _product_file_type;
  _product_file_type product_file;

   typedef uint8_t _setup_changed_type;
  _setup_changed_type setup_changed;

   typedef uint8_t _product_changed_type;
  _product_changed_type product_changed;




  typedef boost::shared_ptr< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> const> ConstPtr;

}; // struct PickitStatus_

typedef ::im_pickit_msgs::PickitStatus_<std::allocator<void> > PickitStatus;

typedef boost::shared_ptr< ::im_pickit_msgs::PickitStatus > PickitStatusPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::PickitStatus const> PickitStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::PickitStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e66b3a740a3e3363c03cbef9c13ce9f6";
  }

  static const char* value(const ::im_pickit_msgs::PickitStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe66b3a740a3e3363ULL;
  static const uint64_t static_value2 = 0xc03cbef9c13ce9f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/PickitStatus";
  }

  static const char* value(const ::im_pickit_msgs::PickitStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Copyright Intermodalics 2014\n\
## This message contains Pick-it status information  ##\n\
\n\
string state\n\
\n\
string setup_file\n\
string product_file\n\
\n\
bool setup_changed\n\
bool product_changed\n\
";
  }

  static const char* value(const ::im_pickit_msgs::PickitStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.setup_file);
      stream.next(m.product_file);
      stream.next(m.setup_changed);
      stream.next(m.product_changed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickitStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::PickitStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::PickitStatus_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
    s << indent << "setup_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.setup_file);
    s << indent << "product_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.product_file);
    s << indent << "setup_changed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.setup_changed);
    s << indent << "product_changed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.product_changed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_PICKITSTATUS_H
