// Generated by gencpp from file im_pickit_msgs/PoseInRobotConvention.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_POSEINROBOTCONVENTION_H
#define IM_PICKIT_MSGS_MESSAGE_POSEINROBOTCONVENTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct PoseInRobotConvention_
{
  typedef PoseInRobotConvention_<ContainerAllocator> Type;

  PoseInRobotConvention_()
    : robot_type()
    , position()
    , orientation()
    , orientation_unit()  {
      position.assign(0.0);

      orientation.assign(0.0);
  }
  PoseInRobotConvention_(const ContainerAllocator& _alloc)
    : robot_type(_alloc)
    , position()
    , orientation()
    , orientation_unit(_alloc)  {
  (void)_alloc;
      position.assign(0.0);

      orientation.assign(0.0);
  }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type_type;
  _robot_type_type robot_type;

   typedef boost::array<double, 3>  _position_type;
  _position_type position;

   typedef boost::array<double, 4>  _orientation_type;
  _orientation_type orientation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _orientation_unit_type;
  _orientation_unit_type orientation_unit;




  typedef boost::shared_ptr< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> const> ConstPtr;

}; // struct PoseInRobotConvention_

typedef ::im_pickit_msgs::PoseInRobotConvention_<std::allocator<void> > PoseInRobotConvention;

typedef boost::shared_ptr< ::im_pickit_msgs::PoseInRobotConvention > PoseInRobotConventionPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::PoseInRobotConvention const> PoseInRobotConventionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "549652ee550f87af479cfa70e3398398";
  }

  static const char* value(const ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x549652ee550f87afULL;
  static const uint64_t static_value2 = 0x479cfa70e3398398ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/PoseInRobotConvention";
  }

  static const char* value(const ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Possible robot types:\n\
# - ABB     (Radians)\n\
# - FANUC   (Degrees)\n\
# - STAUBLI (Degrees)\n\
# - KUKA    (Degrees)\n\
# - UR      (Radians)\n\
\n\
string       robot_type\n\
float64[3]   position\n\
float64[4]   orientation\n\
string       orientation_unit\n\
";
  }

  static const char* value(const ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_type);
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.orientation_unit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseInRobotConvention_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::PoseInRobotConvention_<ContainerAllocator>& v)
  {
    s << indent << "robot_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_type);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "orientation_unit: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.orientation_unit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_POSEINROBOTCONVENTION_H
