// Generated by gencpp from file im_pickit_msgs/SaveSnapshotRequest.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOTREQUEST_H
#define IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct SaveSnapshotRequest_
{
  typedef SaveSnapshotRequest_<ContainerAllocator> Type;

  SaveSnapshotRequest_()
    : snapshot_name()
    , robot_request(false)  {
    }
  SaveSnapshotRequest_(const ContainerAllocator& _alloc)
    : snapshot_name(_alloc)
    , robot_request(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _snapshot_name_type;
  _snapshot_name_type snapshot_name;

   typedef uint8_t _robot_request_type;
  _robot_request_type robot_request;




  typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveSnapshotRequest_

typedef ::im_pickit_msgs::SaveSnapshotRequest_<std::allocator<void> > SaveSnapshotRequest;

typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotRequest > SaveSnapshotRequestPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotRequest const> SaveSnapshotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a7038b273f96eb365eb0416823fefa7";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a7038b273f96eb3ULL;
  static const uint64_t static_value2 = 0x65eb0416823fefa7ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/SaveSnapshotRequest";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string    snapshot_name\n\
bool      robot_request\n\
";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.snapshot_name);
      stream.next(m.robot_request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveSnapshotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::SaveSnapshotRequest_<ContainerAllocator>& v)
  {
    s << indent << "snapshot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.snapshot_name);
    s << indent << "robot_request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.robot_request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOTREQUEST_H
