// Generated by gencpp from file im_pickit_msgs/SaveConfiguration.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_SAVECONFIGURATION_H
#define IM_PICKIT_MSGS_MESSAGE_SAVECONFIGURATION_H

#include <ros/service_traits.h>


#include <im_pickit_msgs/SaveConfigurationRequest.h>
#include <im_pickit_msgs/SaveConfigurationResponse.h>


namespace im_pickit_msgs
{

struct SaveConfiguration
{

typedef SaveConfigurationRequest Request;
typedef SaveConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveConfiguration
} // namespace im_pickit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_pickit_msgs::SaveConfiguration > {
  static const char* value()
  {
    return "0dd17841f9345006b1b64154016fca6c";
  }

  static const char* value(const ::im_pickit_msgs::SaveConfiguration&) { return value(); }
};

template<>
struct DataType< ::im_pickit_msgs::SaveConfiguration > {
  static const char* value()
  {
    return "im_pickit_msgs/SaveConfiguration";
  }

  static const char* value(const ::im_pickit_msgs::SaveConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::im_pickit_msgs::SaveConfigurationRequest> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::SaveConfiguration > 
template<>
struct MD5Sum< ::im_pickit_msgs::SaveConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::SaveConfiguration >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::SaveConfigurationRequest> should match 
// service_traits::DataType< ::im_pickit_msgs::SaveConfiguration > 
template<>
struct DataType< ::im_pickit_msgs::SaveConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::SaveConfiguration >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_pickit_msgs::SaveConfigurationResponse> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::SaveConfiguration > 
template<>
struct MD5Sum< ::im_pickit_msgs::SaveConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::SaveConfiguration >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::SaveConfigurationResponse> should match 
// service_traits::DataType< ::im_pickit_msgs::SaveConfiguration > 
template<>
struct DataType< ::im_pickit_msgs::SaveConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::SaveConfiguration >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_SAVECONFIGURATION_H
