// Generated by gencpp from file im_pickit_msgs/SaveSnapshot.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOT_H
#define IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOT_H

#include <ros/service_traits.h>


#include <im_pickit_msgs/SaveSnapshotRequest.h>
#include <im_pickit_msgs/SaveSnapshotResponse.h>


namespace im_pickit_msgs
{

struct SaveSnapshot
{

typedef SaveSnapshotRequest Request;
typedef SaveSnapshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveSnapshot
} // namespace im_pickit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_pickit_msgs::SaveSnapshot > {
  static const char* value()
  {
    return "90190d82af18bd6fd2d3560080cbe804";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshot&) { return value(); }
};

template<>
struct DataType< ::im_pickit_msgs::SaveSnapshot > {
  static const char* value()
  {
    return "im_pickit_msgs/SaveSnapshot";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshot&) { return value(); }
};


// service_traits::MD5Sum< ::im_pickit_msgs::SaveSnapshotRequest> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::SaveSnapshot > 
template<>
struct MD5Sum< ::im_pickit_msgs::SaveSnapshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::SaveSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::SaveSnapshotRequest> should match 
// service_traits::DataType< ::im_pickit_msgs::SaveSnapshot > 
template<>
struct DataType< ::im_pickit_msgs::SaveSnapshotRequest>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::SaveSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveSnapshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_pickit_msgs::SaveSnapshotResponse> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::SaveSnapshot > 
template<>
struct MD5Sum< ::im_pickit_msgs::SaveSnapshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::SaveSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveSnapshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::SaveSnapshotResponse> should match 
// service_traits::DataType< ::im_pickit_msgs::SaveSnapshot > 
template<>
struct DataType< ::im_pickit_msgs::SaveSnapshotResponse>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::SaveSnapshot >::value();
  }
  static const char* value(const ::im_pickit_msgs::SaveSnapshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOT_H
