// Generated by gencpp from file im_pickit_msgs/SaveSnapshotResponse.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOTRESPONSE_H
#define IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct SaveSnapshotResponse_
{
  typedef SaveSnapshotResponse_<ContainerAllocator> Type;

  SaveSnapshotResponse_()
    : success(false)
    , message()  {
    }
  SaveSnapshotResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;




  typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveSnapshotResponse_

typedef ::im_pickit_msgs::SaveSnapshotResponse_<std::allocator<void> > SaveSnapshotResponse;

typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotResponse > SaveSnapshotResponsePtr;
typedef boost::shared_ptr< ::im_pickit_msgs::SaveSnapshotResponse const> SaveSnapshotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/SaveSnapshotResponse";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool      success\n\
string    message\n\
\n\
";
  }

  static const char* value(const ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveSnapshotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::im_pickit_msgs::SaveSnapshotResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_SAVESNAPSHOTRESPONSE_H
