// Generated by gencpp from file im_pickit_msgs/StatusInvalid.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_STATUSINVALID_H
#define IM_PICKIT_MSGS_MESSAGE_STATUSINVALID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace im_pickit_msgs
{
template <class ContainerAllocator>
struct StatusInvalid_
{
  typedef StatusInvalid_<ContainerAllocator> Type;

  StatusInvalid_()
    {
    }
  StatusInvalid_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }




    static const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  CATEGORY;
     enum { UNRELIABLE_3D_SCENE_COVERAGE_TOO_LOW = 100u };
     enum { UNRELIABLE_2D_SCENE_COVERAGE_TOO_LOW = 101u };
     enum { UNRELIABLE_3D_MODEL_COVERAGE_TOO_LOW = 102u };
     enum { UNRELIABLE_2D_MODEL_CONTOUR_COVERAGE_TOO_LOW = 103u };
     enum { UNRELIABLE_2D_MODEL_SURFACE_COVERAGE_TOO_LOW = 104u };
     enum { UNRELIABLE_2D_MODEL_SURFACE_COVERAGE_TOO_HIGH = 105u };
     enum { UNRELIABLE_MISALIGNED_X_AXIS = 200u };
     enum { UNRELIABLE_MISALIGNED_Y_AXIS = 201u };
     enum { WRONG_SIZE_SMALLER_THAN_X_MIN = 300u };
     enum { WRONG_SIZE_LARGER_THAN_X_MAX = 301u };
     enum { WRONG_SIZE_SMALLER_THAN_Y_MIN = 302u };
     enum { WRONG_SIZE_LARGER_THAN_Y_MAX = 303u };
     enum { WRONG_SIZE_SMALLER_THAN_Z_MIN = 304u };
     enum { WRONG_SIZE_LARGER_THAN_Z_MAX = 305u };
     enum { WRONG_SIZE_SMALLER_THAN_MIN_OBJECT_POINTS = 306u };
     enum { WRONG_SIZE_LARGER_THAN_MAX_OBJECT_POINTS = 307u };
     enum { WRONG_SURFACE_SIDE_EXTERNAL = 400u };
     enum { WRONG_SURFACE_SIDE_INTERNAL = 401u };
     enum { IN_PREVIOUS_IMAGE = 500u };
 

  typedef boost::shared_ptr< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> const> ConstPtr;

}; // struct StatusInvalid_

typedef ::im_pickit_msgs::StatusInvalid_<std::allocator<void> > StatusInvalid;

typedef boost::shared_ptr< ::im_pickit_msgs::StatusInvalid > StatusInvalidPtr;
typedef boost::shared_ptr< ::im_pickit_msgs::StatusInvalid const> StatusInvalidConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > 
      StatusInvalid_<ContainerAllocator>::CATEGORY =
        
          "INVALID"
        
        ;
   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace im_pickit_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'im_pickit_msgs': ['/home/sdrwcs/ROS_Projects/Pickit_ROS/src/im_pickit_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de376df19f3bac290330f837647f3728";
  }

  static const char* value(const ::im_pickit_msgs::StatusInvalid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde376df19f3bac29ULL;
  static const uint64_t static_value2 = 0x0330f837647f3728ULL;
};

template<class ContainerAllocator>
struct DataType< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "im_pickit_msgs/StatusInvalid";
  }

  static const char* value(const ::im_pickit_msgs::StatusInvalid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# These objects (100 <= status <= 999)\n\
# will get a red colored visualization marker.\n\
\n\
string CATEGORY = INVALID\n\
\n\
### Enums:\n\
\n\
uint16 UNRELIABLE_3D_SCENE_COVERAGE_TOO_LOW = 100\n\
uint16 UNRELIABLE_2D_SCENE_COVERAGE_TOO_LOW = 101\n\
uint16 UNRELIABLE_3D_MODEL_COVERAGE_TOO_LOW = 102\n\
uint16 UNRELIABLE_2D_MODEL_CONTOUR_COVERAGE_TOO_LOW = 103\n\
uint16 UNRELIABLE_2D_MODEL_SURFACE_COVERAGE_TOO_LOW = 104\n\
uint16 UNRELIABLE_2D_MODEL_SURFACE_COVERAGE_TOO_HIGH = 105\n\
\n\
uint16 UNRELIABLE_MISALIGNED_X_AXIS = 200\n\
uint16 UNRELIABLE_MISALIGNED_Y_AXIS = 201\n\
\n\
uint16 WRONG_SIZE_SMALLER_THAN_X_MIN = 300\n\
uint16 WRONG_SIZE_LARGER_THAN_X_MAX = 301\n\
uint16 WRONG_SIZE_SMALLER_THAN_Y_MIN = 302\n\
uint16 WRONG_SIZE_LARGER_THAN_Y_MAX = 303\n\
uint16 WRONG_SIZE_SMALLER_THAN_Z_MIN = 304\n\
uint16 WRONG_SIZE_LARGER_THAN_Z_MAX = 305\n\
uint16 WRONG_SIZE_SMALLER_THAN_MIN_OBJECT_POINTS = 306\n\
uint16 WRONG_SIZE_LARGER_THAN_MAX_OBJECT_POINTS = 307\n\
\n\
uint16 WRONG_SURFACE_SIDE_EXTERNAL = 400\n\
uint16 WRONG_SURFACE_SIDE_INTERNAL = 401\n\
\n\
uint16 IN_PREVIOUS_IMAGE = 500\n\
";
  }

  static const char* value(const ::im_pickit_msgs::StatusInvalid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StatusInvalid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::im_pickit_msgs::StatusInvalid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::im_pickit_msgs::StatusInvalid_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_STATUSINVALID_H
