// Generated by gencpp from file im_pickit_msgs/StrArg.msg
// DO NOT EDIT!


#ifndef IM_PICKIT_MSGS_MESSAGE_STRARG_H
#define IM_PICKIT_MSGS_MESSAGE_STRARG_H

#include <ros/service_traits.h>


#include <im_pickit_msgs/StrArgRequest.h>
#include <im_pickit_msgs/StrArgResponse.h>


namespace im_pickit_msgs
{

struct StrArg
{

typedef StrArgRequest Request;
typedef StrArgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StrArg
} // namespace im_pickit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::im_pickit_msgs::StrArg > {
  static const char* value()
  {
    return "8682e79b6a8d3cc445497c38297309bb";
  }

  static const char* value(const ::im_pickit_msgs::StrArg&) { return value(); }
};

template<>
struct DataType< ::im_pickit_msgs::StrArg > {
  static const char* value()
  {
    return "im_pickit_msgs/StrArg";
  }

  static const char* value(const ::im_pickit_msgs::StrArg&) { return value(); }
};


// service_traits::MD5Sum< ::im_pickit_msgs::StrArgRequest> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::StrArg > 
template<>
struct MD5Sum< ::im_pickit_msgs::StrArgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::StrArg >::value();
  }
  static const char* value(const ::im_pickit_msgs::StrArgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::StrArgRequest> should match 
// service_traits::DataType< ::im_pickit_msgs::StrArg > 
template<>
struct DataType< ::im_pickit_msgs::StrArgRequest>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::StrArg >::value();
  }
  static const char* value(const ::im_pickit_msgs::StrArgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::im_pickit_msgs::StrArgResponse> should match 
// service_traits::MD5Sum< ::im_pickit_msgs::StrArg > 
template<>
struct MD5Sum< ::im_pickit_msgs::StrArgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::im_pickit_msgs::StrArg >::value();
  }
  static const char* value(const ::im_pickit_msgs::StrArgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::im_pickit_msgs::StrArgResponse> should match 
// service_traits::DataType< ::im_pickit_msgs::StrArg > 
template<>
struct DataType< ::im_pickit_msgs::StrArgResponse>
{
  static const char* value()
  {
    return DataType< ::im_pickit_msgs::StrArg >::value();
  }
  static const char* value(const ::im_pickit_msgs::StrArgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IM_PICKIT_MSGS_MESSAGE_STRARG_H
