# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from im_pickit_msgs/CameraList.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import im_pickit_msgs.msg

class CameraList(genpy.Message):
  _md5sum = "e437b032a8e9ff1590a662fd97c982f9"
  _type = "im_pickit_msgs/CameraList"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """CameraConfig[] cameras        # List of known cameras.
CameraState[] camera_states   # Corresponding camera states.

================================================================================
MSG: im_pickit_msgs/CameraConfig
# Message fields
string name                                 # name (=namespace) of the camera (unique!)
string serial                               # Serial number.

================================================================================
MSG: im_pickit_msgs/CameraState
uint8 STATE_REGISTERED    = 1
uint8 STATE_CONNECTED     = 2
uint8 STATE_DISCONNECTED  = 3

uint8 state   # Camera state
"""
  __slots__ = ['cameras','camera_states']
  _slot_types = ['im_pickit_msgs/CameraConfig[]','im_pickit_msgs/CameraState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cameras,camera_states

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CameraList, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.cameras is None:
        self.cameras = []
      if self.camera_states is None:
        self.camera_states = []
    else:
      self.cameras = []
      self.camera_states = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.cameras)
      buff.write(_struct_I.pack(length))
      for val1 in self.cameras:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.serial
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.camera_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.camera_states:
        buff.write(_get_struct_B().pack(val1.state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.cameras is None:
        self.cameras = None
      if self.camera_states is None:
        self.camera_states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cameras = []
      for i in range(0, length):
        val1 = im_pickit_msgs.msg.CameraConfig()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.serial = str[start:end].decode('utf-8')
        else:
          val1.serial = str[start:end]
        self.cameras.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.camera_states = []
      for i in range(0, length):
        val1 = im_pickit_msgs.msg.CameraState()
        start = end
        end += 1
        (val1.state,) = _get_struct_B().unpack(str[start:end])
        self.camera_states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.cameras)
      buff.write(_struct_I.pack(length))
      for val1 in self.cameras:
        _x = val1.name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.serial
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.camera_states)
      buff.write(_struct_I.pack(length))
      for val1 in self.camera_states:
        buff.write(_get_struct_B().pack(val1.state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.cameras is None:
        self.cameras = None
      if self.camera_states is None:
        self.camera_states = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cameras = []
      for i in range(0, length):
        val1 = im_pickit_msgs.msg.CameraConfig()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.name = str[start:end].decode('utf-8')
        else:
          val1.name = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.serial = str[start:end].decode('utf-8')
        else:
          val1.serial = str[start:end]
        self.cameras.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.camera_states = []
      for i in range(0, length):
        val1 = im_pickit_msgs.msg.CameraState()
        start = end
        end += 1
        (val1.state,) = _get_struct_B().unpack(str[start:end])
        self.camera_states.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
