# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from im_pickit_msgs/SubfolderContent.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import im_pickit_msgs.msg

class SubfolderContent(genpy.Message):
  _md5sum = "e61ad7c13c96906f44de1e72d7cf413f"
  _type = "im_pickit_msgs/SubfolderContent"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """## Copyright Intermodalics 2014
string                  subfolder_name             ## This is the relative name
im_pickit_msgs/File[]   subfolder_files

================================================================================
MSG: im_pickit_msgs/File
## Copyright Intermodalics 2015
int32        file_id
string       file_name
bool         readonly"""
  __slots__ = ['subfolder_name','subfolder_files']
  _slot_types = ['string','im_pickit_msgs/File[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       subfolder_name,subfolder_files

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SubfolderContent, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.subfolder_name is None:
        self.subfolder_name = ''
      if self.subfolder_files is None:
        self.subfolder_files = []
    else:
      self.subfolder_name = ''
      self.subfolder_files = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.subfolder_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.subfolder_files)
      buff.write(_struct_I.pack(length))
      for val1 in self.subfolder_files:
        buff.write(_get_struct_i().pack(val1.file_id))
        _x = val1.file_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_B().pack(val1.readonly))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.subfolder_files is None:
        self.subfolder_files = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.subfolder_name = str[start:end].decode('utf-8')
      else:
        self.subfolder_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.subfolder_files = []
      for i in range(0, length):
        val1 = im_pickit_msgs.msg.File()
        start = end
        end += 4
        (val1.file_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.file_name = str[start:end].decode('utf-8')
        else:
          val1.file_name = str[start:end]
        start = end
        end += 1
        (val1.readonly,) = _get_struct_B().unpack(str[start:end])
        val1.readonly = bool(val1.readonly)
        self.subfolder_files.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.subfolder_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.subfolder_files)
      buff.write(_struct_I.pack(length))
      for val1 in self.subfolder_files:
        buff.write(_get_struct_i().pack(val1.file_id))
        _x = val1.file_name
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_B().pack(val1.readonly))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.subfolder_files is None:
        self.subfolder_files = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.subfolder_name = str[start:end].decode('utf-8')
      else:
        self.subfolder_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.subfolder_files = []
      for i in range(0, length):
        val1 = im_pickit_msgs.msg.File()
        start = end
        end += 4
        (val1.file_id,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.file_name = str[start:end].decode('utf-8')
        else:
          val1.file_name = str[start:end]
        start = end
        end += 1
        (val1.readonly,) = _get_struct_B().unpack(str[start:end])
        val1.readonly = bool(val1.readonly)
        self.subfolder_files.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
